### ISSUE TITLE
server.js 依赖coinfig.js不存在

### ISSUE THREAD

**Issue by shangxinbo** [sqqihao/EPubBuilder#2]
在server.js require config/config.js ,但包里没有这个文件，运行时会报错

**Comment by sqqihao** [comment]
您好， 你直接打开src目录下的index.html即可看到效果， 身边没带笔记本， 过两天我把配置文件重新提交一下

**Comment by sqqihao** [comment]
添加了config.js， 把npm没用到的依赖删了， 原来用的npm组件版本太低了

**Comment by sqqihao** [comment]
添加了config.js， 把npm没用到的依赖删了， 原来用的npm组件版本太低了
